yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("group/<slug:slug>/", views.group_list, name="group_list"),
    path("", views.index, name="index"),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = 'core.views.page_not_found'


urlpatterns = [
    path("", include("posts.urls", namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
        help_text='Выбрать автора из списка',

    )

    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:15]

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        related_name='author',
        on_delete=models.SET_NULL,
        null=True
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария',
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"Запись: '{self.post}', автор: '{self.author}'"


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=None,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    def __str__(self):
        return f"Последователь: '{self.user}', автор: '{self.author}'"

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
            'image': 'Картинка'
        }
        help_texts = {
            'text': 'Текст нового Поста',
            'group': 'Группа, к которой будет относиться новый пост',
            'image': 'Картинка, которую можно загрузить'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        lables = {'text': 'Текст комментария', }
        help_texts = {
            'text': 'Текст комментария'
        }

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Group, Post, Follow
from .utils import get_page_context

User = get_user_model()

CACHE_TIME = 20


@cache_page(20)
def index(request):
    context = {
        'group_link': 'group_link',
        'author_link': 'author_link',
        'page_obj': get_page_context(Post.objects.all(), request)
    }
    return render(request, 'posts/index.html', context)


def group_list(request, slug):
    group = get_object_or_404(Group, slug=slug)
    context = {
        'group': group,
        'author_link': 'author_link',
        'group_link': 'group_link',
        'page_obj': get_page_context(group.posts.all(), request)
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    user = request.user
    following = user.is_authenticated and user.following.exists()
    context = {
        'author': author,
        'page_obj': get_page_context(author.posts.all(), request),
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(data=request.POST or None)
    comments = post.comments.all()
    following = (
        request.user.is_authenticated
        and post.author.following.filter(user=request.user).exists()
    )
    context = {
        "post": post,
        'form': form,
        'comments': comments,
        'following': following,
    }
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    post = Post(author=request.user)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('posts:profile', request.user.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
        'is_edit': 'is_edit',
    }
    return render(
        request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    follower = Follow.objects.filter(user=request.user).values('author')
    post_list = Post.objects.filter(author__in=follower)
    context = {
        'page_obj': get_page_context(post_list, request),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = User.objects.get(username=username)
    user = request.user
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
        return redirect(
            'posts:profile',
            username=username
        )
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def profile_unfollow(request, username):
    user = request.user
    Follow.objects.get(user=user, author__username=username).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

yatube/templates/posts/add_comment.html
{% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
  {% empty %}
  <p>У данного поста нет комментариев, Будьте первым!.</p>
{% endfor %}

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load thumbnail %}
{% load user_filters %}
{% block  title %}
  {% if not is_edit %}
    Новый пост
  {% else %}
    Редактировать пост
  {% endif %}
{% endblock title %}
  {% block content %} 
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">       
        {% if not is_edit %}
          Добавить запись
        {% else %}
          Редактировать запись
        {% endif %}            
      </div>
      <div class="card-body">        
        <form method="post" action="{% url 'posts:post_create' %}" enctype="multipart/form-data">
          {% csrf_token %}           
          <div class="form-group row my-3 p-3">
            <label for="id_text">
              Текст поста                  
              <span class="required text-danger" >*</span>                  
            </label>
            {{ form.text|addclass:'form-control' }}                
            <small id="id_text-help" class="form-text text-muted">
              Текст нового поста
            </small>                  
          </div>            
          <div class="form-group row my-3 p-3">
            <label for="id_group">
              Группа                 
            </label>
            {{ form.group|addclass:'form-control'}}
            <small id="id_group-help" class="form-text text-muted">
              Группа, к которой будет относиться пост
            </small>
          </div>
          <div class="form-group row my-3 p-3">
            <label for="id_image">
              Картинка                      
            </label>
            <input type="file" name="image" accept="image/*" class="form-control" id="id_image">                      
          </div>
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if not is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}               
            </button> 
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
  {% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}     
{% load static %}
{% load cache %}
{% block title %} YATUBE: подписки {% endblock %}
{% block content %}
{% include 'posts/includes/switcher.html' %}
<h1>Подписки на авторов</h1>
{% for post in page_obj %}
{% include 'posts/includes/article.html' with author_link=True group_link=True  %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load user_filters %}
{% load static %}
{% block title %} {{group.title}} {% endblock %}
{% block content %}
<h1>{{group.title}}</h1>
<p> {{group.description}}</p>
{% for post in page_obj %}
{% include 'posts/includes/article.html' with group_link=False author_link=True %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}     
{% load static %}
{% block title %} YATUBE {% endblock %}
{% block content %}
<h1>Последние обновления на сайте</h1>
{% for post in page_obj %}
{% include 'posts/includes/article.html' with author_link=True group_link=True  %}
{% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endblock content %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} {{ post.text|truncatechars:30 }} {% endblock %}
{% block content %}
<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Дата публикации: {{ post.pub_date|date:"d E Y"  }}
      </li>
      {% if post.group %}   
      <li class="list-group-item">
        Группа: {{ post.group.title }}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      </li>
      <li class="list-group-item">
        Автор: {{post.author.get_full_name}}
      </li>
      {% endif %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора:  <span > {{post.author.posts.count }} </span>
      </li>
      <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
      </li>
    </ul>
  </aside>
  <article class="col-12 col-md-9"> 
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
   
  <p>{{ post.text|linebreaksbr}}</p>
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}" 
        role="button">Редактировать</a>  
  {% include 'posts/add_comment.html' %}
</article>
</div> 
{% endblock content %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} Профайл пользователя {{author.get_full_name}} {% endblock %}
{% block content %}
<div class="mb-5">        
    <h1>Все посты пользователя {{author.get_full_name}} </h1>
    <h3>Всего постов: {{author.posts.count}} </h3>
    {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
</div>   
    {% for post in page_obj %}
    {% include 'posts/includes/article.html' with author_link=False group_link=True %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
{% endblock content %}    